### ISSUE TITLE
Cant install on S7 Edge

### ISSUE THREAD

**Issue by azizLIGHT** [CrazyDude1994/twitch-chat-emotes-overlay#1]
I posted this on reddit but here it is again. Its in reference to [the APK you posted here](https://www.reddit.com/r/forsen/comments/ah0zzb/android_chat_overlay_update/)

The download is weird, cause it's not named as an apk file. Google drive says file type not supported, when downloading. I downloaded it from my browser on mobile instead but had to rename it from twitch-emotes-1.0.1 (no extension) to twitch-emotes-1.0.1.apk. I got to install screen, I see the correct app name, but when I hit install, it tries and fails and says App not installed. Yes I did uninstall the old version. What do

**Comment by CrazyDude1994** [comment]
Hi @azizLIGHT 
I'm sorry it took too long, I finally had some time to look into it.
I'm probably fixed this issue, you can try again with the old link

**Comment by azizLIGHT** [comment]
The install went through successfully for me! I'm currently testing it out now. Thanks for the fix!!
